chore: Repo Initial Maintenance
openedx/edx-notes-api pull request #369
Opened 2023-11-16 10:22 UTC by salman2013

**Description:**

 Initial repo maintenance as per https://docs.openedx.org/en/latest/developers/how-tos/maintain-a-repo.html#how-to-maintain-a-repository

Ticket: https://github.com/orgs/openedx/projects/55/views/1?pane=issue&itemId=41691245

2023-11-16 20:17 UTC, feanil approved these changes
I think it's fine to leave me in this group but it's fine to remove the rest.

2023-11-17 09:57 UTC, salman2013 commented
@feanil are you talking about the 'owner' in catalog.yml?

2023-11-20 06:21 UTC, farhan commented on catalog-info.yaml
> +  annotations:
We should remove `annotations` key altogether
like
https://github.com/openedx/xblock-lti-consumer/blob/8197943d4e4abc6d058c6038500582df47ed493e/catalog-info.yaml

2023-11-20 06:21 UTC, farhan commented on catalog-info.yaml
> +  lifecycle: 'production'
Need extra line

2023-11-20 06:21 UTC, farhan requested changes
requested changes

2023-12-06 15:42 UTC, feanil approved these changes

2023-12-14 13:06 UTC, farhan approved these changes

2023-12-14 13:06 UTC, merged